CREATE SCHEMA IF NOT EXISTS CSEP;

DROP TABLE IF EXISTS CSEP.PRODUCT;

CREATE TABLE CSEP.PRODUCT(
    product_id int8 generated by default as identity,
    user_id bigint,
    bill_number text,
    balance decimal(20,2),
    product_type int4,
    PRIMARY KEY (product_id)
);

INSERT INTO CSEP.PRODUCT(user_id, bill_number, balance, product_type) VALUES
    (1,'9909123845342776', 12345.34, 1),
    (1,'2345467678654534', 1236678.11, 2),
    (2,'9909556788456432', 678.34, 1),
    (2,'8877234534545365', 123443, 1),
    (2,'99093425987865634', 6654323, 2),
    (123,'4456678678567456', 999.99, 1),
    (123,'9786746345632453', 7777.77, 1),
    (123,'4564562414254778', 99988.88, 1),
    (123,'3456567867867342', 777744, 2),
    (123,'3295489676623445', 345667, 1);

COMMIT;